### ISSUE TITLE
General Suggestion

### ISSUE THREAD

**Issue by gep13** [CleanKludge/Cake.Path#11]
`Path` is a very common Class name, as a result, people may run into some conflicts with the class name that you have used here:

https://github.com/CleanKludge/Cake.Path/blob/master/src/Cake.Path/Path.cs

Having spoken about this within the Cake Team, our suggestion would be to change the name, or perhaps internalize the class, so that it isn't exposed to other consuming the addin.

Please let me know if you have any questions.

**Comment by Korthax** [comment]
This is all done now and pushed in release 1.4.0.

Cheers
