### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [CleanKludge/Cake.Path#8]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

https://github.com/cake-build/website/pull/290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Korthax** [comment]
Thanks for the pointers. I'll look at getting this done in (hopefully) the next few days.

**Comment by gep13** [comment]
Nice one!  Please let me know if you have any questions!

**Comment by gep13** [comment]
This was completed here: https://github.com/cake-build/website/pull/346

@Korthax thank you very much for getting this done.
